name: Publish IPFS
on:
  push:
    branches:
      - master
env:
  HOSTNAME: ${{ secrets.HOSTNAME }}
  ROOT_PATH: /

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Checkout repo
      uses: actions/checkout@master

    - name: Build CAR file
      run: |
        ver="<div id=\"version\">Archive Explorer version $(date) Commit $(git rev-parse --short HEAD)</div>"
        sed -i "s#<\!--VERSION PLACEHOLDER-->#$ver#" $GITHUB_WORKSPACE/$ROOT_PATH/index.html
        npm i --global ipfs-car
        ipfs-car pack $GITHUB_WORKSPACE/$ROOT_PATH/ --wrap false --output /tmp/output.car
        ipfs-car roots /tmp/output.car > /tmp/res.txt

    - name: Upload CAR as artifact
      uses: actions/upload-artifact@v4
      with:
        name: archive-explorer-car
        path: /tmp/output.car

    - name: Update DNS
      run: |
        cat /tmp/res.txt
        echo Reading IPFS CID
        IPFS=$(cat /tmp/res.txt)
        echo "Pinning $IPFS"
        if [ -n "$HEPASSWORD" ]; then
          curl -4 "https://_dnslink.$HOSTNAME:$HEPASSWORD@dyn.dns.he.net/nic/update" -d "hostname=_dnslink.$HOSTNAME" -d "txt=dnslink=/ipfs/$IPFS"
        fi
        if [ -n "$DOTOKEN" ]; then
          curl -s -X PATCH -H 'Content-Type: application/json' -H "Authorization: Bearer $DOTOKEN" -d "{\"data\":\"dnslink=/ipfs/$IPFS\"}" "https://api.digitalocean.com/v2/domains/$HOSTNAME/records/$DOID" > /dev/null
        fi
        
